### ISSUE TITLE
Pages show under "wanted" but there are no backlinks listed

### ISSUE THREAD

**Issue by ilium007** [lupo49/dokuwiki-plugin-orphanswanted#17]
I have a large list of "Wanted" pages shown but when I click "Show backlinks" I get:

```
Backlinks

This is a list of pages that seem to link back to the current page.

Nothing was found.
```

However some of them actually show something.

**Comment by marcbavay** [comment]
I've experienced this too.
Rebuilt the index, emptied the browser cache, pb is still here

**Comment by jaller94** [comment]
The plugin counts backlinks on the page itself while DokuWiki does not list those.

**Comment by jaller94** [comment]
A lot of these should be fixed by #27, though I expect more patterns to be not properly ignored by the plugin.
Maybe there is a solution to the parser output of dokuwiki. That way we could be sure it matches with dokuwiki's interpretation of links (and "ignored links").

**Comment by michitux** [comment]
@jaller94 There is no need to parse the pages in the plugin or to use the DokuWiki parser (even though that would be possible, that's actually what the move plugin does) - DokuWiki already extracts all the information you need and puts them in the [metadata index](https://www.dokuwiki.org/devel:metadata#metadata_index). What this plugin should do is simply read this index and check which pages that are referenced in the index exist/don't exist. Feel free to ask me if you need further help/information - either here or via email. I don't have the time to implement and especially test this myself but I am definitely willing to answer questions and give you tips how to implement it.

**Comment by jaller94** [comment]
I read about a function called `getBacklinks()` but wasn't able to find it.
However, the internal RemoteAPI uses `return ft_backlinks($this->resolvePageId($id));`.
`ft_backlinks()` is inside of /inc/fulltext.php. According to it's documentation it "Uses the metadata index."

I was already looking into that. Hope I'll get it working soon.

**Comment by michitux** [comment]
Just using `ft_backlinks()` won't be enough and probably also not fast enough. You probably need to get the content of the index files as the index only allows rather simple searches. You need three files: a) the list of all pages (though some of them might be deleted already) b) the list of all link targets c) the mapping between link targets and the pages. 

When a link target is actually used (i.e. is contained in pages and these pages exist) but the link target does not exist, you have a wanted page. When an existing page is no link target or the link target doesn't have any existing pages, you have an orphan. 

You can use `idx_getIndex` to get the content of index files. In order to get the list of all pages you can use the `getPages()` method of the indexer and you could also use `lookupKey()` in order to get the pages that reference a certain link target (or all link targets by passing an array that contains all link targets that you got from `idx_getIndex`).

**Comment by jaller94** [comment]
Should be fixed in release 2023-05-30, which is now using DokuWiki's internal index.
